<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="EricksonLopez.Pagination" />
    <PackageReference Include="EricksonLopez.Pagination.Abstractions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.DapperExtensions\EricksonLopez.DapperExtensions.csproj" />
  </ItemGroup>


</Project>
