// Copyright © Erickson Lopez. MIT License.
using System;
using System.Diagnostics;
using System.Globalization;
using System.Threading.Tasks;
using Dapper;
using EricksonLopez.DapperExtensions.MultiMap;
using EricksonLopez.DapperExtensions.Showcase.Infrastructure;
using EricksonLopez.DapperExtensions.Showcase.Models;

namespace EricksonLopez.DapperExtensions.Showcase.Levels.Level07_ScalabilityAndPerformance;

/// <summary>
/// Level 7 — Scalability & Performance: Native AOT, Roslyn Source Generators, and Zero-Reflection.
/// </summary>
public static class NativeAotAndPerformanceDemo
{
    public static async Task RunAsync()
    {
        ConsoleHelper.PrintHeader(7, "Scalability & Performance", "Native AOT, [SqlEntity] Source Generators, and Zero-Reflection Hydration");

        using var connection = await ShowcaseDbContext.CreateOpenConnectionAsync().ConfigureAwait(false);
        await ShowcaseDbContext.SeedSampleDataAsync(connection).ConfigureAwait(false);

        ConsoleHelper.PrintStep("1. Direct AOT Hydration with Source-Generated ReadFromDataReader");
        using (var command = connection.CreateCommand())
        {
            command.CommandText = "SELECT id, email, full_name AS FullName FROM customers WHERE id = 1;";
            using var reader = await command.ExecuteReaderAsync().ConfigureAwait(false);

            if (reader.Read())
            {
                // Method generated by Roslyn SqlEntityGenerator at compile-time
                var customer = Customer.ReadFromDataReader(reader);

                ConsoleHelper.PrintInfo("Generated ID", customer.Id);
                ConsoleHelper.PrintInfo("Email", customer.Email);
                ConsoleHelper.PrintInfo("Name", customer.FullName);
                ConsoleHelper.PrintSuccess("Entity hydrated directly from IDataReader without reflection or dynamic IL emit.");
            }
        }

        ConsoleHelper.PrintStep("2. MultiMap Descriptor & Factory AOT Integration");
        var factory = Customer.GetMultiMapReaderFactory();
        ConsoleHelper.PrintInfo("MultiMap Reader Factory", factory.Method.Name);

        var descriptor = new MultiMapDescriptor(
            entityType: typeof(Customer),
            tableName: "customers",
            columnNames: ["id", "email", "full_name"],
            readerFactory: factory);

        ConsoleHelper.PrintInfo("Descriptor Table", descriptor.TableName);
        ConsoleHelper.PrintInfo("Descriptor EntityType", descriptor.EntityType.Name);
        ConsoleHelper.PrintInfo("Descriptor Columns Count", descriptor.ColumnNames.Length);

        ConsoleHelper.PrintStep("3. Performance & Throughput Verification");
        const int iterations = 10_000;
        var sw = Stopwatch.StartNew();

        for (int i = 0; i < iterations; i++)
        {
            var dummy = new Product
            {
                Id = i,
                Sku = $"SKU-{i}",
                Name = "Performance Test",
                Price = 10.0m,
                StockQuantity = 5
            };
            _ = dummy.Id;
        }

        sw.Stop();
        ConsoleHelper.PrintSuccess($"Processed {iterations:N0} instances in {sw.ElapsedMilliseconds}ms (Zero reflection overhead).");

        ConsoleHelper.PrintSuccess("Level 7 completed successfully.");
    }
}
