// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.DapperExtensions.SourceGenerators;

/// <summary>
/// Generates zero-reflection Native AOT reader mappers for types decorated with the <c>SqlEntityAttribute</c>.
/// </summary>
[Generator]
public class SqlEntityGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Determines whether a syntax node is a candidate for source generation.
    /// </summary>
    /// <param name="node">The syntax node to inspect.</param>
    /// <returns><see langword="true"/> if the node is a type declaration with attributes; otherwise, <see langword="false"/>.</returns>
    public static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        => node is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter classes, structs and records with attributes
        IncrementalValuesProvider<TypeDeclarationSyntax> typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsSyntaxTargetForGeneration(node),
                transform: static (ctx, _) => (TypeDeclarationSyntax)ctx.Node)
            .Where(static typeDecl => typeDecl is not null);

        IncrementalValueProvider<(Compilation Compilation, ImmutableArray<TypeDeclarationSyntax> Types)> compilationAndTypes =
            context.CompilationProvider.Combine(typeDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndTypes, static (spc, source) => Execute(source.Compilation, source.Types, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types, SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
            return;

        foreach (var typeDeclaration in types.Distinct())
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var declaredSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration, context.CancellationToken);
            if (declaredSymbol is not INamedTypeSymbol typeSymbol || typeSymbol.TypeKind == TypeKind.Error || string.IsNullOrWhiteSpace(typeSymbol.Name))
                continue;

            bool hasSqlEntityAttribute = typeSymbol.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name is "SqlEntityAttribute" or "SqlEntity");

            if (!hasSqlEntityAttribute)
                continue;

            var generatedCode = GenerateMapperForType(typeSymbol);
            var nsPrefix = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? "Global"
                : typeSymbol.ContainingNamespace.ToDisplayString().Replace('.', '_');
            var hintName = $"{nsPrefix}_{typeSymbol.Name}_SqlEntityMapper.g.cs";
            context.AddSource(hintName, SourceText.From(generatedCode, Encoding.UTF8));
        }
    }

    private static string GenerateMapperForType(INamedTypeSymbol typeSymbol)
    {
        var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeName = typeSymbol.Name;
        var typeKind = typeSymbol.TypeKind == TypeKind.Struct ? "struct" : "class";
        var isRecord = typeSymbol.IsRecord ? "record " : string.Empty;

        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && !p.IsReadOnly && p.SetMethod is not null)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using EricksonLopez.DapperExtensions.MultiMap;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial {isRecord}{typeKind} {typeName}");
        sb.AppendLine("{");

        // Factory method required by MultiMapBuilder AOT path
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Zero-reflection source-generated factory method for Native AOT multi-mapping.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Func<IDataReader, object> GetMultiMapReaderFactory()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return static reader => ReadFromDataReader(reader);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Reads and populates a new instance of <see cref=\"{typeName}\"/> from an open <see cref=\"IDataReader\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {typeName} ReadFromDataReader(IDataReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(reader);");
        sb.AppendLine($"        var instance = new {typeName}();");

        foreach (var prop in properties)
        {
            var propName = prop.Name;
            var propType = prop.Type.ToDisplayString();
            var conversionType = (prop.Type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T && named.TypeArguments.Length == 1)
                ? named.TypeArguments[0].ToDisplayString()
                : prop.Type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString();

            sb.AppendLine($"        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            var ordinal = reader.GetOrdinal(\"{propName}\");");
            sb.AppendLine($"            if (!reader.IsDBNull(ordinal))");
            sb.AppendLine("            {");
            sb.AppendLine($"                var rawValue = reader.GetValue(ordinal);");
            sb.AppendLine($"                instance.{propName} = rawValue is {conversionType} directVal ? directVal : ({propType})Convert.ChangeType(rawValue, typeof({conversionType}));");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (Exception ex) when (ex is IndexOutOfRangeException or ArgumentException)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Column not present in result set; leave default value.");
            sb.AppendLine("        }");
        }

        sb.AppendLine("        return instance;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
